version: "3.3"
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - spring_datasource_url=jdbc:postgresql://db:5432/test_db
    depends_on:
      - "db"
    ports:
      - '8080:8080'
    networks:
      - my-network
  db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'test_db'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    networks:
      - my-network

networks:
  my-network:
    external: false
    