version: "3.3"
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    environment:
      - spring_datasource_url=jdbc:postgresql://db:5432/test_db
    depends_on:
      - "db"
    ports:
      - '8080:8080'
    expose:
      - '8080'
    command: java -jar ./spring-example-0.0.1-SNAPSHOT.jar
    networks:
      - my-network
  db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'test_db'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./db-data/:/docker-entrypoint-initdb.d/
    networks:
      - my-network

networks:
  my-network:
    external: false
    